### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by lxa520** [rogerclarkmelbourne/radioddity_gd-77_cps#45]
Do you have any good advice on this software，In software operation

**Comment by rogerclarkmelbourne** [comment]
I have a page of bugs in the GD77 firmware and also hardware

http://www.rogerclark.net/list-of-radioddity-gd-77-bugs/

For CPS people request feature to add "Move Up" / "Move Down" for Channels and Digital Contacts (like I add for Zone). I start this but not have time to finish yet.

I will ask for list from the community.


Some requests require changes to firmware (see list)

Do you have contact with programmer for firmware ?
(I would like to change the firmware but it is difficult to read from the GD77)

Changes to firmware e.g.

Multiple squelch levels (not just Normal and Tight)

Not need Rx Group to be set. (Probably if Rx Group is set to None then enabled "Monitor" mode

Multiple power settings (not just High and Low). Some people use local gateway and prefer very low power e.g. 100mW or perhaps 10mW

DMR ID has a problem because it only allocates 8 characters for each ID. This needs to be 16 to be compatible with Digital Contacts

DMR ID is data is taken in preference to Digital Contact data if same ID in both DB.

Allow access to DMR ID address 0x30000 - 0x4FFF **without need to reboot+ SK2+Green+#**

**Comment by rogerclarkmelbourne** [comment]
Hi @lxa520 

I think the CPS is written well, but one big problem with the system design is the choice to use the binary data format used for the GD-77 as the file format that is saved to disk.

I think it would have been better if the PC file was some other non-binary format, probably XML.

I know this would make the file much bigger (probably many times larger) but would make it easier to open old codeplugs to be opened in newer versions of the CPS.


Comms with the GD-77 could be improved if larger file transfers were allowed and also perhaps if the GD-77 implemented a wider range of commands.

I presume that the GD-77 firmware must cache Writes to Flash and then only erase when the data cached data needs to be written to more than one page in Flash

I'm a bit concerned if perhaps the transfer is slow because every Write of 32 bytes is erasing a 2k or 4k page in Flash, as the Flash will wear out really quickly if this is what the firmware is doing

I write firmware as well as C# (if you see my other repos they are for STM32 and also for nRF5x)

**Comment by lxa520** [comment]
If CPS is stored in XML, it will be a big project. I've seen Motorola, which is stored in XML

**Comment by rogerclarkmelbourne** [comment]
Yes. CPS would be much bigger as XML (not sure how much bigger, if perhaps very short tag and attribute names were used.

BTW. I see some old code in the CPS for both XML and also Serialised conversion, but they are not used.

**Comment by rogerclarkmelbourne** [comment]
FYI

I've changed my VS project to add conditional compilation for firmware version 3.0.6 and now for firmware 3.1.x (added extra build targets)

I've also added constants for the values used in the RX Group list e.g. number of channels per group etc

Also I refactored the data (model) classes for the RX Group into separate classes, to isolate changes in the data storage (model) from GUI (view) and functions (controller) i.e like MVC design pattern


So hopefully I can support both 3.0.6 and 3.1.x in the same codebase.

**Comment by rogerclarkmelbourne** [comment]
BTW. I think you changed something with Contacts, and perhaps added compaction to remove empty space.

I noticed in you 3.1.1 CPS that if I delete a contact from the middle of the list, and add contact, its added to the end not the middle (like in 3.0.6)
I think you may have done the same for Channels but I need to check

I have not decompiled 3.1.1 as it takes too long to decompile and then make it recompile again, its quicker for us to make changes to the 3.0.6 codebase, by looking at changes to the data in the codeplug format

**Comment by rogerclarkmelbourne** [comment]
One more question...

What has changed in firmware 3.1.2 ???

Someone email me 3.1.2 firmware, but I can't see any change.

**Comment by lxa520** [comment]
firmware bug fixed, function no change

**Comment by rogerclarkmelbourne** [comment]
What bug is fixed.

We have list of bugs and no bugs on our list if fixed. So this must be bug not on our list

**Comment by rogerclarkmelbourne** [comment]
Was bug fixed on this list 

http://www.rogerclark.net/list-of-radioddity-gd-77-bugs/

**Comment by rogerclarkmelbourne** [comment]
BTW. Some people tell me bug fix in 3.1.2 is for Factor Settings, but I think there is a still a problem and it is not fixed

**Comment by rogerclarkmelbourne** [comment]
I have a question.

In CPS 3.1.1, if I delete a Contact then add a contact, the Contact is added at the end of the list.

Did you add a "Compact" feature to remove empty Contacts from the list ?
(I did this for Zones)
I think you may have also made the same change to Channels, but I have not tested yet

**Comment by lxa520** [comment]
What's the problem with factory reset？

I have seen your list of changes，
The way of zone modification (zone move down and zone move up, compact zone) is wrong.

When the contact is deleted, the content related to the contact is refreshed (for example, the  group receive list).

**Comment by rogerclarkmelbourne** [comment]
No.
Its not a problem. I just need to update my CPS to fix some problems which you already fixed.

**Comment by rogerclarkmelbourne** [comment]
FYI

ActiveClient will not work now, because DMR-MARC no longer have CSV files.

Only file available now is CSVQ ("quoted" version)

Also fields are different.


I added some support for this in my CPS, but I still need to integrate full support for DMR ID mode.

PS.

There is a bug in the firmware, because DMR ID database (from ActiveClient) is checked first.

Digital Contacts should be checked first.

Also DMR ID system is not good, because it only allocates 8 chars for callsign, but Digital Contacts has 16 characters

so if same ID is in both DMR ID and Digital Contacts, then firmware loads 8 chars from DMR ID data not 16 chars from Digital Contacts

So if callsign + name is longer than 8 chars, the display is not so good

Better if DMR ID uses 16 characters and also Digital Contacts is checked first.

Perhaps you can add "version 0002" to support 16 chars per DRM ID.
I know this has less total records in DMR ID, e.g. currently DMR ID is 4 bytes for ID and 8 byes for Name.
= 12 bytes

Total records is 10920 x 12 bytes = 131040 (just under 128k)

So if data record is 4 bytes ID + 16 bytes name = 20 bytes, then total number of records is only 
128k/ 20 = 6553

With header data this would give 6550 records instead of 10920

I know its marketing decision to have more than 10,000 records, but I think it is better if users have an option to have 16 chars for name e.g. have 2 different modes. Version 1 is 8 chars for name, and Version 2 is 16 chars for name.

Most users would prefer 16 chars per name.

I hope perhaps you can convince marketing to agree this change.

(its very easy to change in firmware ;-)

**Comment by lxa520** [comment]
This will not be added at the moment

**Comment by lxa520** [comment]
eazfuscator.net  , you can deobfuscate it ?

**Comment by rogerclarkmelbourne** [comment]
Don;t know about eazfuscator. 
I've not needed to view source from programs obfuscated with that utility

**Comment by rogerclarkmelbourne** [comment]
What is firmware 3.1.3  It is on new GD-77 but not released on Radioddity website :-(

http://www.rogerclark.net/gd-77-firmware-3-1-3-seen-in-new-radios/

Also.

Is inverted (black/white) display hardware or firmware change ?

**Comment by rogerclarkmelbourne** [comment]
@lxa520 

FYI.
Its probably not worth you fixing, since I am writing a much improved export / import feature,  but...

This for loop , in channels import is redundant and just makes imports go slower

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps/blob/master/DMR/ChannelsForm.cs#L275

the iterator variable "item" not really used.

**Comment by rogerclarkmelbourne** [comment]
BTW. There is also a bug in Signalling, the default is set to 1 and this should be 3 to comply with the recommendations in the DMR spec

Also the TX Wakeup TOT (ms)    value should be around 320 (nearest value in the CPS is 325)

**Comment by rogerclarkmelbourne** [comment]
Closed due to no response in over 1 month
