### ISSUE TITLE
GD-77-- Quiet on receive-- anyone else find this also??

### ISSUE THREAD

**Issue by ZL2WMS-MIKE** [rogerclarkmelbourne/radioddity_gd-77_cps#56]
My GD-77 seems to be quiet on receive, I can only sometime hear my local repeater, I can trigger the repeater and come up on ZL-TRBO (http://trbo.arec.info:42420/MinimalNetwatch) which shows us here who is on and where etc.

I have heard of one more GD-77 which has the same issue , are there more, and has someone worked how to sort this other than sending the H/H back to Radioddity???

Thank you 

Mike  ZL2WMS, Nelson, New Zealand

**Comment by rogerclarkmelbourne** [comment]
Mike,

I'm not sure what you mean.

When someone is on the repeater, does the green LED light to indicate that its receiving the carrier + data.

Did you try using Monitor Mode ?
This can only be activated by assigning it to a button. e.g. in the Buttons screen, I SK1 (short press) assigned to Monitor 

If you can hear people in Monitor mode that you cant hear otherwise, it means you have not added all the required TG's into your Digital Contacts and assigned them to the Rx Group you are using for that repeater.

Cheers
Roger 
VK3KYY

**Comment by ZL2WMS-MIKE** [comment]
Thank you Roger, I will ask Andrew ZL2HZ to help me….

 

I was told to push the PTT button when the green light shows….I do this and I still hear nothing …

 

Mike

 

Mike and Helen Sheat

16 Parere Street

Nelson South

Nelson

New Zealand 7010

ZL2WMS

 

Ph: 03 548 0988

Mike 027 2616 192

Helen 027 763 6284

Our Em:  <mailto:mikesheat@xtra.co.nz> mikesheat@xtra.co.nz 

Helen's Em: hmlsheat@gmail.com

**Comment by rogerclarkmelbourne** [comment]
Hi Mike

For some reason you posted your home address and phone number when you replied to the comment.
I have edited the comment to remove them, but they can't be fully removed in the comment history, as thats the way GitHub works.

I suspect your email program adds a big header with all your details. So its best to just click the link to view the issue on Github rather than hitting reply in your email client.

Re: Pressing PTT

I think you need to speak to someone locally about this, as it sounds like you are describing how to access a reflector, or something else to do with the general operation of DMR.

How you operate on your local DMR network may be different to how other systems are setup.

This github repo and its issues are to report bugs with the CPS.

Its not a forum about how to operate on DMR or how to configure a codeplug to discuss firmware issues on the GD77, as these are all out of scope of this piece of software.

**Comment by ZL2WMS-MIKE** [comment]
Hi Roger, appreciate your reply. Sorry but I replied to the other reply via my email software...

Just a note to say that I am accessing our repeater direct not through a reflector.

It is nothing to do with what I am doing itm is what the radio is not doing, and that is hearing. But hey thanks for your replies, I will ask the guys here and if not I will sending the radio back to Radioddity...

73s ..... Mike ZL2WMS
