### ISSUE TITLE
import channel order differs

### ISSUE THREAD

**Issue by riku2015** [rogerclarkmelbourne/radioddity_gd-77_cps#61]
when importing channels from cvs, the order will be not same as the list have.
dont know if this is a bug or it suppose to do this.

**Comment by rogerclarkmelbourne** [comment]
This was not intentional

Originally when the channels were imported it deleted all channels first, but I changed this so that there are two options.

Import (updates and appends), or Clear and Import (Deletes all channels first)

The idea with the update and append was so that a new set of channels could be added by just having the CSV with those channels in it.

With Clear and import, I clear the channels and the contacts and the Rx Lists, but I could not clear the Zones, because if I clear the zones, I don't seem to be able to add new zones :-(

I have not noticed that the order of the channels has changed in the main list in the CPS.

However I have noticed recently that something strange has happened with the Zones and they seem to be sorted alphabetically, and I don't think I did this manually.


Anyway. I will investigate the channel ordering problem

**Comment by riku2015** [comment]
will it help if i send somehow my cvs file to you, you will see middle of zone comes other zone, has nothing to do with zone or channel alphabet order

**Comment by forkoz** [comment]
There is definitely an ordering issue. I exported all channels and tried to import after re-ordering. The channels fill in to wherever, even going back to where they were. If I delete everything, same problem.

If I delete all, add a bunch of blank channels and then do the import most of the order is maintained. Unfortunately in this case all channels are at 100, 101, 102, etc and future channels go to 1, 2, 3, etc.

It seems to revolve around whether a channel was was previously filled in or not. If its fresh the importer is likely to keep the arrangements.

**Comment by rogerclarkmelbourne** [comment]
Ah

I think I need to change the user interface to add an explanation of how this works.

If you just import, it will not change the order, it just updates and appends

If you change the order, you need to use the option to "Import Clear all"

However, "Import Clear all" does not remove zones, or remove channels from the zones.

I can delete all but one zone, but if I delete that, the CPS breaks :-(

I guess I could delete all zones, except the first one, and clear the first zone. 
(This may fix the other bug !)

Anyway, I obviously need to improve things and explain the operation .

The github issues are not a good place to document this, so I'll need to write a new blog post


BTW. Would you prefer if there was just one Import button, but after the button was pressed, there were more options to either completely clear (except the last zone) or update and leave the zones etc alone.

The problem is that if I delete all the zones, they get reconstructed in the order they are required by a channel. i.e as I add a new channel, if it uses a zone that doesnt exist, it has to create the zone and add the channel to the zone. Same for Rx Group lists.

So the order of the Zones and the Rx Group lists don't necessarily end up the same as they were before, because I don't export the zones, and Rx Group lists.


BTW.  I forgot to say, another good option is the codeplug exporter / importer written by Colin G4ELM

PS. I know there is another tool that does codeplug upload / download, but I'm not sure it does export/import

**Comment by forkoz** [comment]
I just tried the new one and its even worse now. Import clear all as you said deletes all the contacts so anything not defaulted to a channel goes missing. Why? Order is still not kept. Entries I moved to the middle of the list go right back to the top where they were. 

My goal is to keep all the channels together. Lets say I have 200 channels some simplex and some repeater. I want to keep the simplex together so the list isn't a mashup. Order of the zones seemed alphabetical and that was ok. Previous version didn't eat my unbound contacts.

**Comment by riku2015** [comment]
i have used ctrl + a then delete all channels (that will also empty the zones and scanlists) then i imported/updated its only way without press deleteall(what also deletes contacts, and that is unwanted because the order of them will differ from original)

**Comment by rogerclarkmelbourne** [comment]
Looks like the changes to the channels export are not a good idea.

I'll reinstate the old functionality

**Comment by rogerclarkmelbourne** [comment]
I have removed the new features in the latest commit d79f776f7a1b6b97fb9fad796b8f605035b188e9

**Comment by forkoz** [comment]
Well now order is the same with the caveat it has to be manually re-numbered. Unfortunately all zones are empty. Is it not possible to have something in the middle where you can still re-number the channels?

 On the beta "delete last channel" version it seemed to work the best besides channel ordering. Not possible to just add the channel # column back?

**Comment by rogerclarkmelbourne** [comment]
Take a look at the official CPS. 

AFIK. Channels only imports Channels, and Contacts only imports Contacts

There is no export / import feature for any other sections, and no linkage between sections

Unfortunately, creating Zones , Contacts and Rx Groups as required by a channel during the import, is almost certain to cause the Zones, Contacts and Rx Groups to change order.

Zones can be reordered (in my version of the CPS), but nothing else can.
Nothing can be re-ordered in the official CPS

**Comment by forkoz** [comment]
I've never actually used the official CPS, just this one. The re-ordering is being done in excel and the question was why it deviated from the CSV when importing. Probably just need the channel # column back, not deleting the whole thing (now that I see what it did originally). Unless that's impossible.

**Comment by footloosejava** [comment]
I just posted an issue about this:
https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps/issues/65

Also, the reordering happens even if a blank codeplug template is used with all groups removed ahead of time, for 'import/update' and 'import clear all'.

I looked at the code and cannot see how it is happening.

Is there a conflict with the GUI thread so that the GUI is interrupting the full update? (I ask because I don't see it happening on short lists). 

Maybe the Form is reordering the appearance and not just in the Channels object??
